# Generated by Django 2.2.26 on 2022-03-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
