# Generated by Django 2.2.26 on 2022-03-07 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
