# Generated by Django 2.2.26 on 2022-03-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0003_userprofiletest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
    ]
