# Generated by Django 2.2.26 on 2022-03-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0004_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={},
        ),
    ]
