# Generated by Django 2.2.26 on 2022-03-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0004_remove_userprofile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='host',
        ),
        migrations.RemoveField(
            model_name='userprofiletest',
            name='website',
        ),
        migrations.AddField(
            model_name='userprofiletest',
            name='host',
            field=models.BooleanField(default=False),
        ),
    ]
