# Generated by Django 2.2.26 on 2022-03-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0005_auto_20220308_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
