# Generated by Django 2.2.26 on 2022-03-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0005_auto_20220307_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='userprofiletest',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
