# Generated by Django 2.2.26 on 2022-03-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0006_auto_20220307_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='shareLocation',
        ),
        migrations.AddField(
            model_name='userprofiletest',
            name='shareLocation',
            field=models.BooleanField(default=False),
        ),
    ]
