# Generated by Django 2.2.26 on 2022-03-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0008_auto_20220307_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiletest',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userprofiletest',
            name='request',
        ),
        migrations.RemoveField(
            model_name='userprofiletest',
            name='shareLocation',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='host',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shareLocation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
