# Generated by Django 2.2.26 on 2022-03-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0009_auto_20220307_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiletest',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofiletest',
            name='shareLocation',
            field=models.BooleanField(default=False),
        ),
    ]
