# Generated by Django 2.2.26 on 2022-03-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0011_userprofiletest_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiletest',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
