# Generated by Django 2.2.26 on 2022-03-07 19:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('radar', '0012_userprofiletest_accept'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfileTest',
            new_name='UserProfileT',
        ),
    ]
