# Generated by Django 2.2.26 on 2022-03-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0013_auto_20220307_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='userId_fk',
        ),
        migrations.AlterField(
            model_name='friendlist',
            name='friendId_fk',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='UserProfileT',
        ),
    ]
