# Generated by Django 2.2.26 on 2022-03-07 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0014_auto_20220307_1925'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendList',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
