# Generated by Django 2.2.26 on 2022-03-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0017_auto_20220307_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
