# Generated by Django 2.2.26 on 2022-03-07 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0019_friendlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='userId_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radar.UserProfile'),
        ),
    ]
