# Generated by Django 2.2.26 on 2022-03-07 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0020_auto_20220307_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(default=True)),
                ('hasArrived', models.BooleanField(default=False)),
                ('destination', models.CharField(max_length=128, unique=True)),
                ('userId_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radar.UserProfile')),
            ],
        ),
    ]
